// Demo seed feedback dipindah dari App.tsx (fallback sebelum API load).
// Identik dengan FeedbackSeeder Laravel.
import type { Feedback } from "../domain/types";

export const initialFeedbacks: Feedback[] = [
    {
      code: "ISTURA-2026-0039",
      rating: 5,
      bookingEase: 5,
      service: 4,
      recommend: 5,
      highlights: ["Penyambutan", "Cerita sejarah"],
      improvements: [],
      comment: "Informasi jadwal dan konfirmasi sangat jelas.",
      allowPublish: true,
      submittedAt: "23 Mei 2026, 16.20 WIB",
    },
    // -----------------------------------------------------------------
    // Seed 20 feedback dummy untuk demo pagination + skenario beragam:
    // - rating 1..5 tersebar (bukan hanya 4-5)
    // - kombinasi highlights/improvements yang berbeda
    // - allowPublish true/false bercampur
    // - beberapa comment kosong (tidak diwajibkan oleh form)
    // - tanggal submittedAt urut kronologis Jan -> Mei 2026
    // -----------------------------------------------------------------
    {
      code: "ISTURA-2026-0001",
      rating: 5,
      bookingEase: 5,
      service: 5,
      recommend: 5,
      highlights: ["Penyambutan", "Tur area", "Cerita sejarah", "Penjelasan pemandu"],
      improvements: [],
      comment: "Anak-anak sangat antusias mendengar cerita pemandu. Terima kasih!",
      allowPublish: true,
      submittedAt: "15 Januari 2026, 14.05 WIB",
    },
    {
      code: "ISTURA-2026-0002",
      rating: 4,
      bookingEase: 5,
      service: 4,
      recommend: 4,
      highlights: ["Tur area", "Dokumentasi"],
      improvements: ["Waktu kunjungan"],
      comment: "Durasi tur terasa singkat, sayang sekali tidak sempat ke perpustakaan.",
      allowPublish: true,
      submittedAt: "22 Januari 2026, 13.40 WIB",
    },
    {
      code: "ISTURA-2026-0003",
      rating: 3,
      bookingEase: 4,
      service: 3,
      recommend: 3,
      highlights: ["Cerita sejarah"],
      improvements: ["Penjelasan pemandu", "Akses informasi"],
      comment:
        "Suara pemandu kurang terdengar di belakang, mungkin perlu pengeras suara untuk rombongan besar.",
      allowPublish: false,
      submittedAt: "4 Februari 2026, 14.10 WIB",
    },
    {
      code: "ISTURA-2026-0004",
      rating: 5,
      bookingEase: 5,
      service: 5,
      recommend: 5,
      highlights: ["Cerita sejarah", "Penjelasan pemandu", "Fasilitas"],
      improvements: [],
      comment: "Komunitas kami merasa diapresiasi. Materi pemandu sangat lengkap.",
      allowPublish: true,
      submittedAt: "12 Februari 2026, 15.20 WIB",
    },
    {
      code: "ISTURA-2026-0005",
      rating: 4,
      bookingEase: 4,
      service: 5,
      recommend: 4,
      highlights: ["Penjelasan pemandu", "Dokumentasi"],
      improvements: ["Akses informasi"],
      comment:
        "Akan sangat membantu jika di website tersedia denah area kunjungan supaya rombongan bisa siap-siap.",
      allowPublish: true,
      submittedAt: "19 Februari 2026, 12.40 WIB",
    },
    {
      code: "ISTURA-2026-0006",
      rating: 2,
      bookingEase: 3,
      service: 2,
      recommend: 2,
      highlights: [],
      improvements: ["Waktu kunjungan", "Fasilitas", "Penjelasan pemandu"],
      comment:
        "Slot terasa terburu-buru karena agenda kepresidenan, dan area istirahat untuk rombongan terbatas.",
      allowPublish: false,
      submittedAt: "26 Februari 2026, 15.30 WIB",
    },
    {
      code: "ISTURA-2026-0007",
      rating: 5,
      bookingEase: 5,
      service: 5,
      recommend: 5,
      highlights: ["Penyambutan", "Tur area", "Cerita sejarah", "Dokumentasi", "Penjelasan pemandu", "Fasilitas"],
      improvements: [],
      comment: "Pengalaman terbaik bagi mahasiswa kami. Recommended!",
      allowPublish: true,
      submittedAt: "5 Maret 2026, 13.10 WIB",
    },
    {
      code: "ISTURA-2026-0008",
      rating: 4,
      bookingEase: 5,
      service: 4,
      recommend: 4,
      highlights: ["Penyambutan", "Cerita sejarah"],
      improvements: ["Dokumentasi"],
      comment: "",
      allowPublish: true,
      submittedAt: "12 Maret 2026, 14.05 WIB",
    },
    {
      code: "ISTURA-2026-0009",
      rating: 5,
      bookingEase: 5,
      service: 5,
      recommend: 5,
      highlights: ["Penyambutan", "Fasilitas"],
      improvements: ["Akses informasi"],
      comment:
        "Petugas sangat ramah membantu rombongan disabilitas. Akan lebih baik jika info aksesibilitas dipajang di halaman utama.",
      allowPublish: true,
      submittedAt: "19 Maret 2026, 14.20 WIB",
    },
    {
      code: "ISTURA-2026-0010",
      rating: 3,
      bookingEase: 4,
      service: 3,
      recommend: 3,
      highlights: ["Penyambutan"],
      improvements: ["Fasilitas", "Lainnya"],
      comment: "Toilet untuk rombongan besar antri panjang. Mungkin perlu petunjuk arah toilet tambahan.",
      allowPublish: false,
      submittedAt: "26 Maret 2026, 12.45 WIB",
    },
    {
      code: "ISTURA-2026-0011",
      rating: 4,
      bookingEase: 4,
      service: 5,
      recommend: 4,
      highlights: ["Cerita sejarah", "Penjelasan pemandu"],
      improvements: ["Dokumentasi"],
      comment: "Foto bersama di akhir kunjungan kurang terkoordinasi.",
      allowPublish: true,
      submittedAt: "2 April 2026, 13.30 WIB",
    },
    {
      code: "ISTURA-2026-0012",
      rating: 5,
      bookingEase: 5,
      service: 5,
      recommend: 5,
      highlights: ["Penyambutan", "Tur area", "Penjelasan pemandu"],
      improvements: [],
      comment: "Siswa kami pulang dengan banyak inspirasi. Tetap pertahankan!",
      allowPublish: true,
      submittedAt: "9 April 2026, 15.40 WIB",
    },
    {
      code: "ISTURA-2026-0013",
      rating: 1,
      bookingEase: 2,
      service: 1,
      recommend: 1,
      highlights: [],
      improvements: ["Akses informasi", "Penjelasan pemandu", "Waktu kunjungan", "Lainnya"],
      comment:
        "Konfirmasi WhatsApp datang H-1, padahal kami sudah booking jauh hari. Harap koordinasi internal diperbaiki.",
      allowPublish: false,
      submittedAt: "16 April 2026, 13.05 WIB",
    },
    {
      code: "ISTURA-2026-0014",
      rating: 4,
      bookingEase: 5,
      service: 4,
      recommend: 5,
      highlights: ["Cerita sejarah", "Fasilitas"],
      improvements: ["Lainnya"],
      comment: "Mohon disediakan area sholat yang lebih dekat dari titik kumpul rombongan.",
      allowPublish: true,
      submittedAt: "23 April 2026, 14.10 WIB",
    },
    {
      code: "ISTURA-2026-0015",
      rating: 5,
      bookingEase: 5,
      service: 5,
      recommend: 5,
      highlights: ["Penyambutan", "Tur area", "Dokumentasi"],
      improvements: [],
      comment: "",
      allowPublish: true,
      submittedAt: "30 April 2026, 13.50 WIB",
    },
    {
      code: "ISTURA-2026-0016",
      rating: 4,
      bookingEase: 3,
      service: 5,
      recommend: 4,
      highlights: ["Penyambutan", "Penjelasan pemandu"],
      improvements: ["Akses informasi"],
      comment:
        "Pendaftaran online cukup membantu, tapi senior kami kesulitan mengetik NIK. Mungkin bisa disediakan opsi bantuan.",
      allowPublish: true,
      submittedAt: "4 Mei 2026, 13.10 WIB",
    },
    {
      code: "ISTURA-2026-0017",
      rating: 5,
      bookingEase: 5,
      service: 5,
      recommend: 5,
      highlights: ["Cerita sejarah", "Penjelasan pemandu", "Fasilitas"],
      improvements: [],
      comment: "Konten edukatif yang sangat layak dijadikan rujukan studi sejarah.",
      allowPublish: true,
      submittedAt: "7 Mei 2026, 13.40 WIB",
    },
    {
      code: "ISTURA-2026-0018",
      rating: 3,
      bookingEase: 4,
      service: 3,
      recommend: 3,
      highlights: ["Tur area"],
      improvements: ["Penjelasan pemandu"],
      comment: "Akan sangat baik jika tersedia opsi pemandu berbahasa Inggris untuk rombongan internasional.",
      allowPublish: false,
      submittedAt: "12 Mei 2026, 14.20 WIB",
    },
    {
      code: "ISTURA-2026-0019",
      rating: 2,
      bookingEase: 3,
      service: 2,
      recommend: 2,
      highlights: ["Cerita sejarah"],
      improvements: ["Fasilitas", "Akses informasi"],
      comment: "Sinyal di area dalam cukup terbatas, sulit untuk live update kegiatan komunitas.",
      allowPublish: false,
      submittedAt: "14 Mei 2026, 15.10 WIB",
    },
    {
      code: "ISTURA-2026-0020",
      rating: 5,
      bookingEase: 5,
      service: 5,
      recommend: 5,
      highlights: ["Penyambutan", "Cerita sejarah", "Dokumentasi"],
      improvements: [],
      comment: "Anak-anak SD kami sangat senang, terutama saat sesi cerita sejarah.",
      allowPublish: true,
      submittedAt: "20 Mei 2026, 13.20 WIB",
    },
];
