[program:istura-scheduler]
command=__PHP_BINARY__ artisan schedule:work
directory=__DEPLOY_PATH__
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=__SUPERVISOR_USER__
redirect_stderr=true
stdout_logfile=/var/log/supervisor/istura-scheduler.log
stopwaitsecs=60
