[program:istura-queue]
command=__PHP_BINARY__ artisan queue:work database --sleep=3 --tries=3 --timeout=90 --memory=256
directory=__DEPLOY_PATH__
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=__SUPERVISOR_USER__
redirect_stderr=true
stdout_logfile=/var/log/supervisor/istura-queue.log
stopwaitsecs=3600
